GET http://localhost:3000/colores HTTP/1.1

###

GET http://localhost:3000/colores/0 HTTP/1.1

###

POST http://localhost:3000/colores HTTP/1.1
content-type: application/json

{
    "color": "verde"
}

###

PUT http://localhost:3000/colores/2 HTTP/1.1
content-type: application/json

{
    "color": "amarillo"
}

###

DELETE http://localhost:3000/colores/2 HTTP/1.1
content-type: application/json

###